version: '3'
services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
    ports:
      [3306:3306]
    volumes:
      - ./db_files/my_dump.sql:/docker-entrypoint-initdb.d/dump.sql